language: cpp
matrix:
  include:
  - os: windows
   install: 
      - choco install windows-sdk-10-version-1809-all
    env:
     - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
    script:
     - export PATH=$MSBUILD_PATH:$PATH
     - MSBuild.exe JenkinsTest.sln -t:Rebuild -p:Configuration=Release
