language: cpp
matrix:
  include:
  - os: windows
    env:
     - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
    script:
     - export PATH=$MSBUILD_PATH:$PATH
     - MSBuild /p:Configuration=Release JenkinsTest.sln
